 services:
  app:
   build:
      dockerfile: ./Dockerfile
   command:
      - "gunicorn"
      - "mysite19.wsgi:application"
      - "--bind"
      - "0.0.0.0:8000"
   ports:
      - "8000:8000"
   logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push

  grafana:
    image: grafana/grafana:9.3.8
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"